### ISSUE TITLE
referenceList

### ISSUE THREAD

**Issue by kyledecot** [jsl/placemaker#1]
The gem doesn't currently return the referenceList portion of the response.

**Comment by jsl** [comment]
The latest version (0.0.2), which I just pushed a minutes ago, adds parsing for this section.  It also cleans up a bunch of other things in the gem.  I think this should fix your issue, but if not, please re-open.

Also, please note that I also added this gem to rubygems, so you can do a regular 'gem install placemaker' to install this gem in the future and add it as a standard dependency in your application.
